version: '3.7'

services:
  bot:
    image: kirillbobykin/hakeshonassybot:lastest
    restart: always
    environment:
      DOTENV_CONFIG_PATH: /run/secrets/production_config
    secrets:
      - production_config

  api:
    image: kirillbobykin/hakeshonassybot:lastest
    command: npm run api
    restart: always
    ports:
      - 80:3000/tcp
    environment:
      DOTENV_CONFIG_PATH: /run/secrets/production_config
    secrets:
      - production_config

secrets:
  production_config:
    file: .env.production
