# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 13.x
    services:
      mongodb:
        image: mongo:4.2.6
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          MONGO_DB_NAME: hakeshonassydb_test
          MONGO_URL: mongodb://localhost:27017
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'
  dependabot-automerge:
    continue-on-error: true
    runs-on: ubuntu-latest
    needs: [ test, lint ]
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-url: https://fastify-dependabot-merge-app-5uewp47fja-uc.a.run.app/
