---
name: Deploy latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_image:
    name: Push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login docker
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make docker-login-ci
      - name: Release image
        run: make docker-release
  deploy_image:
    name: Deploy image
    runs-on: ubuntu-latest
    needs: push_image
    steps:
      - name: Deploy to swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_SWARM_SSH_HOST }}
          username: ${{ secrets.DOCKER_SWARM_SSH_USERNAME }}
          key: ${{ secrets.DOCKER_SWARM_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DOCKER_SWARM_SSH_PORT }}
          script: docker service update --image kirillbobykin/hakeshonassybot:${GITHUB_SHA::8} hakeshonassybot_bot
