---
name: Push image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_image:
    name: Push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login docker
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make docker-login-ci
      - name: Release image
        run: make docker-release
